joint_num: 24
joint_list:
  - head
  - neck
  - l_sho_r
  - r_sho_r
  - l_sho_p
  - r_sho_p
  - l_arm_y
  - r_arm_y
  - l_arm_p
  - r_arm_p
  - l_wrist
  - r_wrist
  - l_hip_y
  - r_hip_y 
  - l_hip_r  
  - r_hip_r  
  - l_hip_p  
  - r_hip_p  
  - l_knee
  - r_knee
  - l_ank_p 
  - r_ank_p 
  - l_ank_r  
  - r_ank_r
joint_id:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
joint_servo:
  - XL320
  - XL320
  - XL320
  - XL320
  - XL320
  - XL320
  - XL320
  - XL320
  - XL320
  - XL320
  - XL320
  - XL320
  - AX12A
  - AX12A
  - MX28
  - MX28
  - MX28
  - MX28
  - MX28
  - MX28
  - MX28
  - MX28
  - MX28
  - MX28
XL320:
  addr_torque_enable: 24
  size_torque_enable: 1
  addr_goal_pos: 30
  size_goal_pos: 2
  addr_present_pos: 37
  size_present_pos: 2
AX12A:
  addr_torque_enable: 24 
  size_torque_enable: 1
  addr_goal_pos: 30
  size_goal_pos: 2
  addr_present_pos: 36
  size_present_pos: 2
MX28:
  addr_torque_enable: 24
  size_torque_enable: 1
  addr_goal_pos: 30
  size_goal_pos: 2
  addr_present_pos: 36
  size_present_pos: 2