pose_list:
- initial_offset
initial_offset:
  desc: Posisi inisial robot ketika semua sudut masukan adalah 0
  motion:
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]
    - [0, 1, 2]